### PR TITLE
Added zh_TW

### PR DESCRIPTION
**Pull request by olivertzeng**
# Pull Request Template

## Description
translated zh_TW

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] My commits follow the commit standards of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by oae** [comment]
Could you please rebase and update the PR? Thanks.

**Comment by oae** [comment]
There is also this #197 PR. Should I close the other one?

**Comment by olivertzeng** [comment]
> There is also this #197 PR. Should I close the other one? @aerowolf 

Maybe I should diff through our differences per string and try to merge them

**Comment by olivertzeng** [comment]
> There is also this #197 PR. Should I close the other one? @aerowolf 

Oh just viewed that that's simplified Chinese not traditional Chinese

**Comment by olivertzeng** [comment]
> There is also this #197 PR. Should I close the other one? @aerowolf 

Traditional Chinese: zh_TW
Simplified Chinese: zh_CN
you should merge both of them

**Comment by olivertzeng** [comment]
> There is also this #197 PR. Should I close the other one? @aerowolf 

Oh I see, it had the merge issue because I've renamed zh to zh_CN because the zh is the Simplified Chinese version. So what I will do is I'll remove the zh_CN file so that you can merge them

**Comment by olivertzeng** [comment]
> There is also this #197 PR. Should I close the other one? @aerowolf 

Ok I've done the work for you, now you can close his PR, because I've merged your latest changes and replaced zh.po with zh_CN.po with @aerowolf's translations.

**Pull request closed without merging**
