### PR TITLE
Add support for Gnome 45 

### LINKED ISSUE #210: [Feature Request] Add GNOME 45 Support
GNOME 45 is in beta now, Please add support for it to ensure compatibility with the latest version of GNOME and provide users with access to new features and improvements.

### LINKED ISSUE #221: Add support for gnome 45
Hi, today I received the GNOME 45 update via the Arch repo, but I found that the extension doesn't support it yet. Please add GNOME 45 support.

Thanks for this great extension!

### PR DESCRIPTION
**Pull request by Totto16**
# Pull Request 

## Description
This is the PR  for Gnome 45 support
Fixes #210 
Fixes #221

This is now READY TO BE MERGED 🎉 

This is nearly ready and a MAJOR change in many cases.
The new extension only supports Gnome 45 >= and uses esm imports.

I suggest creating a new branch for the `legacy` version of the app (bugfixes etc) , and create a separate one / use the `master` branch for any GNOME Shell >= 45 development and versions

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist
- [x] My code follows the style guidelines of this project
- [x] My commits follow the commit standards of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

## What has changed

I followed the guide [here](https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extension-js) for some basic steps

- [x]  ESM: that means the whole structure of the rollup build and some other stuff is broken, it was refactored to genrate correct imports

- [x] extension.js vs prefs.js differences in imports: yet another problem, that is solves easily in rollup, by mapping internal typed modules to different strings to resolve at runtime

- [x] shell-version: this extension now only supports gnome 45 >=

- [x] extension.js exports default class: this was also changed

- [x]  extensionUtils:  extensionUtils is no longer present, most of the methods are either properties on the ExtensionBase class (both The Extension and the Preferences inherit from that) and must be given to each functions, that earlier used the extensionUtils module 😓 

- [x] other module changes ❓ : the whole package is typed correctly now, it took some minor manual typing, since there are no types for some module yet, but the rest is from build from GIR types

- [x]  Logging: log() has been deprecated, use console.log, or console.error / warn instead

- [x] don't use `initTranslations()` but specify `gettext-domain`  in `metadata.json`, as suggested in the porting guide.

- [x] Clutter.Event changes: all properties on events where refactored to getter functions

## Version ranges

Since multiple distributions are supported, we have to deal / support with multiple versions of some GI libs.

This is done with runtime checks and is also fully typed. 

That is only done for libgda 5.0 and 6.0, since we have types for that.

Her is a list of some version ranges, we officially support.
version ranges:
- Gda 5.0-6.0 (typed and runtime checked) #225 
- Shell 12 - 13 (not yet typed, works atm) #225 
- Clutter 12-13 (not entirely correct type, but nearly correct) #225 
- St 12-13 (not yet typed, works atm) #225 
- Cogl 12-13 (not yet typed, works atm) #225 
- Meta 12-13 (not yet typed, works atm) #225 

A note on Clutter >=12:
Clutter introduced a BREAKING change, in v13.0 that modifies the key/button/scroll event members, they made them to getters instead of properties...
So to maintain the version compatibility I made some not so clean typing, this has to be changed, once we have types for that.
Maybe we can also drop support for v12 entirely.

## TODOs

- [x] cleanup code in some areas
- [x] fix ESM imports
- [x] typings are correct by using [these packages](https://github.com/gjsify/types) and some minor manual typings
- [x] fix gettext error
- [x] fix event changes: properties to getter functions
- [x] fix images not being stored
- [x] some settings don't work correctly. see [this comment](https://github.com/oae/gnome-shell-pano/pull/222#issuecomment-1773450482), fixed in v4
- [x] fix audio not working, bug was already fixed in beta v4
- [x] deal with version / version ranges and types, see above or in the comments below, postponed to #225
- [x] complete the checklist
- [x] more manual tests on all supported distributions?  not done
- [x] approve changes / code review? (done manually myself 😓 ) (does someone voluntary to review 116 changed files ? 😂 ) 

## Beta v4 zip

The build does work atm (also without all dev packages installed), but anyhow, here is a build of the extension, that works on my Gnome 45 Machine ™️  (ATTENTION for ubuntu 23.10 or debian beta users, you need libgda 6.0, that isn't available as .deb yet, you have to build it yourself 😓 or as a workaround, you can remove the constraint and it will likely work, due not for sure in all cases! )

ATTENTION: this has some known bugs, see above in TODOs

[pano_beta_4_gnome_45.zip](https://github.com/oae/gnome-shell-pano/files/13198706/pano_beta_4_gnome_45.zip)

Last changed: 29.10.2023

### CODE REVIEW

**Comment by Totto16** [comment]
[pano_beta_gnome45.zip](https://github.com/oae/gnome-shell-pano/files/12908022/pano_beta_gnome45.zip)


This is an example build of the extension, since atm rollup can't resolve the import correctly, I had to do that manually, so this is a beta build, that works on my Gnome 45 Machine (ATTENTION for ubuntu 23.10 users, you need libgda 6.0, that isn't available as .deb yet, you have to build it yourself 😓 )

**Comment by rysete** [comment]
Hi, I'm running that beta.zip and here's my feedback until now:
Arrow keys don't work to navigate between items;
Esc does not close the "pano board";

other than that, everything seems works well, without crashes and visually without other bugs for me (on fedora 39 anyway).
I hope this helps

**Comment by Totto16** [comment]
Yes, thanks, I am still having similar issues, and I am debugging them ❤️ 👍🏼

**Comment by rysete** [comment]
the beta v3 is Working fine here too, I'm will do some tests, with links, imgaes etc. But for now it fells awesome.
Play audio when copying is working for you?

**Comment by Totto16** [comment]
I didn't test the audio yet, since I have it disabled 😓 
But i will test it 👍🏼

**Comment by RushingAlien** [comment]
Hello, I have been using the beta for a while now, images doesn't seem to be stored in the clipboard

**Comment by Totto16** [comment]
> Hello, I have been using the beta for a while now, images doesn't seem to be stored in the clipboard

true, I didn't see that yet, I guess more debugging work 😓

**Comment by rysete** [comment]
hey! I've been having this problem for a few days now, after restarting the system or closing the session and logging in again, the last previously copied text is automatically pasted into the gnome global search bar and ignores restrictions such blacklist and keep session only.

**Comment by Thesola10** [comment]
Hey, I'm having issues building your branch, below are the error messages.

```
Unknown type:  {
    "name": "gpu",
    "transfer-ownership": "none"
} 
Marking as unknown!
Unknown type:  {
    "name": "logical_monitor",
    "transfer-ownership": "none"
} 
Marking as unknown!
    Error: Failed to import Clutter in St, not installed or accessible.
```

Am I missing something? I added `clutter-13` to the library path as below, but it still doesn't work:

```patch
diff --git a/package.json b/package.json
index 189a8d0..40340a7 100644
--- a/package.json
+++ b/package.json
@@ -7,7 +7,7 @@
   "scripts": {
     "build": "yarn run lock:types && yarn run build:types && yarn run build:ts && yarn run gen:locale && yarn run build:extension",
     "clean": "yarn run clean:ts && yarn run build:types",
-    "lock:types": "rm -rf docs-lock.json && cross-env XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/share/gir-1.0:/usr/share/gnome-shell:/usr/lib/mutter-12:/usr/lib/mutter-11:/usr/lib64/mutter-12:/usr/lib64/mutter-11 yarn run gi-ts config --lock",
+    "lock:types": "rm -rf docs-lock.json && cross-env XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/share/gir-1.0:/usr/share/gnome-shell:/usr/lib/mutter-13:/usr/lib/mutter-12:/usr/lib/mutter-11:/usr/lib64/mutter-12:/usr/lib64/mutter-11 yarn run gi-ts config --lock",
     "build:types": "yarn run clean:types && gi-ts generate",
     "gen:locale": "yarn run ts-node scripts/generateLocale.ts",
     "clean:types": "rm -rf ./@types",
```

**Comment by Totto16** [comment]
> Hey, I'm having issues building your branch, below are the error messages.
> 
> ```
> Unknown type:  {
>     "name": "gpu",
>     "transfer-ownership": "none"
> } 
> Marking as unknown!
> Unknown type:  {
>     "name": "logical_monitor",
>     "transfer-ownership": "none"
> } 
> Marking as unknown!
>     Error: Failed to import Clutter in St, not installed or accessible.
> ```
> 
> Am I missing something? I added `clutter-13` to the library path as below, but it still doesn't work:
> 
> ```diff
> diff --git a/package.json b/package.json
> index 189a8d0..40340a7 100644
> --- a/package.json
> +++ b/package.json
> @@ -7,7 +7,7 @@
>    "scripts": {
>      "build": "yarn run lock:types && yarn run build:types && yarn run build:ts && yarn run gen:locale && yarn run build:extension",
>      "clean": "yarn run clean:ts && yarn run build:types",
> -    "lock:types": "rm -rf docs-lock.json && cross-env XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/share/gir-1.0:/usr/share/gnome-shell:/usr/lib/mutter-12:/usr/lib/mutter-11:/usr/lib64/mutter-12:/usr/lib64/mutter-11 yarn run gi-ts config --lock",
> +    "lock:types": "rm -rf docs-lock.json && cross-env XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/share/gir-1.0:/usr/share/gnome-shell:/usr/lib/mutter-13:/usr/lib/mutter-12:/usr/lib/mutter-11:/usr/lib64/mutter-12:/usr/lib64/mutter-11 yarn run gi-ts config --lock",
>      "build:types": "yarn run clean:types && gi-ts generate",
>      "gen:locale": "yarn run ts-node scripts/generateLocale.ts",
>      "clean:types": "rm -rf ./@types",
> ```

likely you have the types in some other directory, I also had that error IIRC, but i fixed it somehow 🤷🏼 ...
 but I plan to not generate types manually anymore, since there's a [better source](https://github.com/gjsify/types) for GIR types, so in the future you don#t have to have these anymore, many thinsg are still WIP atm, but after this all is finished, you should be able to build it locally, :)

**Comment by Thesola10** [comment]
Thanks, build now goes much further, until
```
[!] Error: 'registerClass' is not exported by node_modules/@girs/gobject-2.0/gobject-2.0.js, imported by src/utils/gjs.ts
```

**Comment by Totto16** [comment]
> Thanks, build now goes much further, until
> 
> ```
> [!] Error: 'registerClass' is not exported by node_modules/@girs/gobject-2.0/gobject-2.0.js, imported by src/utils/gjs.ts
> ```

Yeah I am currently rewriting many things, the build doesn#t work atm, but soon ™️

**Comment by Thesola10** [comment]
Okay, got it to build, fails to load with `ambiguous indirect export: languages`

**Comment by Totto16** [comment]
@Thesola10 
I will inform you, when the build finally works, I know that it doesn't atm, but it didn't work before that either, I had to fix imports by hand, and now I'm trying to fix that :) It takes some time 😓

**Comment by Totto16** [comment]
The 4 version now is buildable, and works, it seems that some bugs were also fixed, like the displaying of images, the audio doesn't work and the other errors by @rysete weren't checked, maybe you can check again @rysete , that would be nice 😄

**Comment by bermudi** [comment]
> The 4 version now is buildable, and works, it seems that some bugs were also fixed, like the displaying of images, but the audio still doesn't work and the other errors by @rysete weren't checked, maybe you can check again @rysete, that would be nice 😄

you are incredible!

**Comment by rysete** [comment]
The bugs reported by me sees fixed now, I'm still tryna reproduce them but for a first view, a common use,  looks much better. @Totto16

**Comment by jacobflanagan** [comment]
I'm so glad this exists for now. I'm on Debian (Gnome 45 Experimental) and Beta 3 worked without fuss. Beta 4 complained about a gda version 6 requirement (only gda 5 is available from apt; likely the same issue as Ubuntu?). Instead of trying to build anything, I removed the version=6.0 requirement from the gda import in extension.js and everything seems fine. Images work great now!

**Comment by Totto16** [comment]
> I'm so glad this exists for now. I'm on Debian (Gnome 45 Experimental) and Beta 3 worked without fuss. Beta 4 complained about a gda version 6 requirement (only gda 5 is available from apt; likely the same issue as Ubuntu?). Instead of trying to build anything, I removed the version=6.0 requirement from the gda import in extension.js and everything seems fine. Images work great now!

Yes it is the same "issue" as in ubuntu, since both ubuntu and debian only ship libga5.0...

The extension onyl support GDA 6.0 officially, that was already the case before my refactoring for Gnome 45
I don't know the reason, whey we need gda >= 6, but maybe we don't? @oae  Can you help there?

Anyway, it worked for me also with the apt for gda 5.0 and than I built gda 6.0 from source and installed it...

The core problem, that still needs discussion, is the "hopefully, propably" support of more versions.
What I mean with that is, that e.g. I used some >=x version specifications, with using the types for version x, so we hope, that these API's still work with >x, which they likely and in 99% will, but we don#t know for sure...

So we need solutions for all supported OS and version mixes...

There are a few optuions:

- manually testing if everything works as expected in a version range, maybe constraint versions to >=x>=y
- setting exact versions, and provide some deb, etc. packages for exatcly the needed versions 
- using some typescript magix and runtime magic to use multiple types, so that we can esnure, that everything works as expected

Another problem is the type in general, they are very unpopular among extension developers, so they are not always present for the newest / used version and some where made manually... 

This is overall a huge issue and we should adress this, before updateng the extension officially and publishing it for gnome 45...

Anyone feel free to correct me or  throw suggestions at me 😄

**Comment by Totto16** [comment]
> Great job @Totto16. I was able to get this built on Fedora 39 and it works well. Fedora 39 has the following libgda versions installed so maybe it is safe to drop down to libgda 5?
> 
> ```
> $ rpm -qa |grep gda
> libgda5-5.2.10-17.fc39.x86_64
> libgda-6.0.0-6.fc39.x86_64
> gdal-libs-3.7.2-1.fc39.x86_64
> libgdata-0.18.1-9.fc39.x86_64
> libgda-sqlite-6.0.0-6.fc39.x86_64
> libgda5-devel-5.2.10-17.fc39.x86_64
> libgda-6.0.0-6.fc39.i686
> libgda-devel-6.0.0-6.fc39.x86_64
> ```

It might really be, since it worked without constraint earlier, do you now, by any chance, which actual version you use (to test use e.g version=6.0, if it fails it might say, since another version is loaded or since it's not installed, than try with version=5.0 and report the eventual error, since the extension beta zip "ships"  with >=6.0 it has to use 6.0, unless you changed the extension.js file?

**Comment by jdoss** [comment]
I assume it is using the most recent version because that's what is is in the packages.json. I didn't make any changes on my end. I just checked out your PR and symlinked it per the development instructions. 

One thing I noticed was two entries for when I do a screenshot.

image

image

**Comment by Totto16** [comment]
> I assume it is using the most recent version because that's what is is in the packages.json. I didn't make any changes on my end. I just checked out your PR and symlinked it per the development instructions.
> 
> One thing I noticed was two entries for when I do a screenshot.
> 
> image
> 
> image
So its using GDA 6.0 👍🏼 

This seems strange, as no one else has this issue with this branch 🤔 

Does it also happen with text (than it would indicate a duplicate instance or listener of some sort)

Otherwise I don't know 🤷🏼‍♂️  Try to restart the session by logging out or rebooting

If that doesn't work, use = in the extension js for every >= and if an error occurs, say which version you have installed / loaded, chnage it back to >= until it works, if you have the list of used version I can maybe debug it or pinpoint the issue

**Comment by jdoss** [comment]
I figured it out. I am still using Gpaste to work around this issue https://github.com/oae/gnome-shell-pano/issues/190 and I turned off image support in that extension and the issue went away. Sorry for the noise!

**Comment by hax0r31337** [comment]
I found that sounds works in my case, I built the extension from [73a1845](https://github.com/Totto16/gnome-shell-pano/commit/73a18457d0b60a31fa1f3b1d6e886a6fce362d47).
I guess the alert sound not working is caused by `gsound` not installed

```
$ sudo pacman -Q | grep gsound
gsound 1.0.3-3
```

**Comment by Thesola10** [comment]
Well this should be clear to merge, been using it for a while and everything, including images, URL previews, sound, etc. works just fine.

**Comment by Totto16** [comment]
> Well this should be clear to merge, been using it for a while and everything, including images, URL previews, sound, etc. works just fine.

Yes thats true, I also found out, after restarting, that the soudn works xD, it seems that something was wrong on my side, I restarted again  and it still worked

**Comment by Totto16** [comment]
Yes it's nearly mergeable, I try to look over everything again and adjust the libgda version, to support also ubuntu 23.10 and debian beta 
👍🏼

**Comment by Totto16** [comment]
By looking at the code I now also noticed, that we already have a runtime check if we are using gda 5 or 6 😓  xD

**Comment by Totto16** [comment]
@oae 
This is now ready to be merged, 🎉  it was tested by multiple persons including me extensively, it seems good so far.

Like said in the top comment / description, I suggest creating a new branch for the `legacy`version of the app, so that eventual bug / security fixes can be made to the version supporting gnome < 45. I added this to the README, so if that isn't done, we would have to edit that file again.

**Comment by oae** [comment]
@Totto16 thank you for this awesome work, I will take a look at this and merge it this weekend.

**Comment by bermudi** [comment]
maxresdefault

**Comment by jacobflanagan** [comment]
Just wanted to point out I still seem to have this issue mentioned by @rysete  (using beta 4 on debian+gnome):

> hey! I've been having this problem for a few days now, after restarting the system or closing the session and logging in again, the last previously copied text is automatically pasted into the gnome global search bar and ignores restrictions such blacklist and keep session only.

This is obvious is with vanilla gnome that starts in the application view upon login.

**Comment by oae** [comment]
I have created a new release and uploaded it to EGO.

**Comment by ScislaC** [comment]
> I have created a new release and uploaded it to EGO.

Awesome to hear! Given that it's a couple days later, is there an issue since it's still not showing on EGO?

**Comment by oae** [comment]
> > I have created a new release and uploaded it to EGO.
> 
> Awesome to hear! Given that it's a couple days later, is there an issue since it's still not showing on EGO?

It is not reviewed on ego yet

**Comment by ScislaC** [comment]
Wow, I had no clue they had a review process. Thanks for the information!

**Comment by ulville** [comment]
I'm sorry if it's inappropriate but maybe we should notice @justperfection _(one of the core ego reviewers)_ in case it had flown under the radar. Since it's a pretty popular extension, a lot of people are probably waiting for it to be on EGO before upgrading to GNOME 45 or feel disappointed seeing it's not available for them after the upgrade.

Again, I'm aware it's a pretty big upgrade with a lot of changes and reviewing it can take longer than a smaller extension, so excuse me if I'm being impetuous

**Comment by bermudi** [comment]
> in case it had flown under the radar...

probably a good idea, I have been getting updates for other extensions that weren't compatible when the new Gnome version came out but Pano still appears as incompatible with Gnome 45

**Comment by justperfection** [comment]
@ulville I'll review it soon.

**Comment by justperfection** [comment]
Ok, rejected since it had some issues. Feel free to ping me, once you finished the fixes. I can review it on GitHub before you posting it to ego.

**Comment by Totto16** [comment]
> Ok, rejected since it had some issues. Feel free to ping me, once you finished the fixes. I can review it on GitHub before you posting it to ego.

Is there a list with the issues? Can we / you open an issue for the errors ?

**Comment by oae** [comment]
I am currently working on them. Here is the list;

1. [x] Please remove `init()` method (line 1238 prefs.js). Not needed.

2. [x]  You are doing too much in the constructor of the default class you are exporting (line 3279 extension.js):
    That is breaking three ego rules:
    - https://gjs.guide/extensions/review-guidelines/review-guidelines.html#only-use-initialization-for-static-resources
    - https://gjs.guide/extensions/review-guidelines/review-guidelines.html#destroy-all-objects
    - https://gjs.guide/extensions/review-guidelines/review-guidelines.html#disconnect-all-signals
    
    Please move them to enable and null those out/ destroy / disconnect signals in disable. 

3. [x] `isEnabled` is a bad practice (line 3348 extension.js).
    You really don't need it to check something like line 3315, 3300 and 3429.

4. [ ] Please remove the import versions.

5. [ ] Don't use `var`. Use `let` and `const` instead.

6. [ ] Extensions cannot use `run_dispose()` (line 252 and 405 extension.js):

    > This function should only be called from object system implementations.

    https://gjs-docs.gnome.org/gobject20~2.0/gobject.object#method-run_dispose

7. [x] Please use `TextDecoder` instead of `byteArray` (line 222 extension.js):
    https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder

**Comment by Totto16** [comment]
> I am currently working on them. Here is the list;
> 
>     1. [x]  Please remove `init()` method (line 1238 prefs.js). Not needed.
> 
>     2. [x]   You are doing too much in the constructor of the default class you are exporting (line 3279 extension.js):
>        That is breaking three ego rules:
>        
>        * https://gjs.guide/extensions/review-guidelines/review-guidelines.html#only-use-initialization-for-static-resources
>        * https://gjs.guide/extensions/review-guidelines/review-guidelines.html#destroy-all-objects
>        * https://gjs.guide/extensions/review-guidelines/review-guidelines.html#disconnect-all-signals
>        
>        Please move them to enable and null those out/ destroy / disconnect signals in disable.
> 
>     3. [x]  `isEnabled` is a bad practice (line 3348 extension.js).
>        You really don't need it to check something like line 3315, 3300 and 3429.
> 
>     4. [ ]  Please remove the import versions.
> 
>     5. [ ]  Don't use `var`. Use `let` and `const` instead.
> 
>     6. [ ]  Extensions cannot use `run_dispose()` (line 252 and 405 extension.js):
>        > This function should only be called from object system implementations.
>        
>        
>        https://gjs-docs.gnome.org/gobject20~2.0/gobject.object#method-run_dispose
> 
>     7. [x]  Please use `TextDecoder` instead of `byteArray` (line 222 extension.js):
>        https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder

Some notes from my point of view, since I worked with gnome 45 and types on this:

- We need those versions, since we rely on them with types, if another version then the ones specified is used, there might be runtime errors 😓 

- So the reviewer can say, that we are running to much in a method, thats sad and interesting at the same point. I f we need to run this all, what would we do than?? 🤔  (I am not sure if we need to, but if we would need to...)

- the vars are generated by rollup afaik, so thats just a a rollup setting (I think, I am not that advanced with rollup)

**Comment by Totto16** [comment]
@justperfection 
On this sentence from @oae I am not sure if it is word by word from the review:
>  You are doing too much in the constructor of the default class you are exporting (line 3279 extension.js):
That is breaking three ego rules:


"doing to much" really confused me, but I think I understood what you / he meant

**Comment by oae** [comment]
@justperfection is there any reason why we should remove the import versions?

**Comment by justperfection** [comment]
Yes, GNOME Shell already specified the versions on Shell process's initiation.
For prefs, the versions already specified by the parent module.

btw, your extension is using too much third party libraries in the package (as we discussed on [GNOME Matrix Channel](https://matrix.to/#/!hCGqHbXRuMrvWnudnP:gnome.org/$42VtygDXhOGgrtwXZZ1OzkrrJRwVWTjFxGZfg0DPHiw?via=gnome.org&via=matrix.org&via=envs.net)).
I'll give you a pass for this version since users waiting for the port but please fix that for the next version.

**Comment by Totto16** [comment]
> Yes, GNOME Shell already specified the versions on Shell process's initiation. For prefs, the versions already specified by the parent module.
> 
> btw, your extension is using too much third party libraries in the package (as we discussed on [GNOME Matrix Channel](https://matrix.to/#/!hCGqHbXRuMrvWnudnP:gnome.org/$42VtygDXhOGgrtwXZZ1OzkrrJRwVWTjFxGZfg0DPHiw?via=gnome.org&via=matrix.org&via=envs.net)). I'll give you a pass for this version since users waiting for the port but please fix that for the next version.

But can you help me out here:

Clutter 12 vs. 13 had breaking changes, if we support multiple distros, can we assure, that only v 13 is loaded without using 
versioned imports????

We are using types, to get type safety and to GUARANTE no runtime errors in e.g. Clutter calls.

So is there an official list, from EXACT version that ship with  each distro on GNOME???

I would say no, since on Ubuntu 23.10 we have Gda 5.0 and on other distros 6.0, how would we say, we support both versions, when there's no import version, would we have to check at runtime if we are using v5.0 v6.0 or potentially in the future v 7.0???

Please explain to me, why exactly version are bad, since I don't get it???

And additionally, we use >= version specifiers, so that we support muliple ranges, like mentioned with the GDa example... see also 
#225

**Comment by schnz** [comment]
Sorry for the intrusion, I just stumbled upon this issue. I had just rewritten the [gTile](https://github.com/gTile/gTile) extension for Gnome 45. It wasn't yet submitted to EGO because the preference dialog is still missing in the rewritten version. But I also use versioned imports to allow proper type-checking during compile/transpile time.

So I would also be highly interested in a best-practice guide on how to develop (type-safe) extensions without versioned imports. Or even any kind of guide that gives a little background information about the topic of GJS imports. Until this moment, I assumed that the version of the imported libraries solely depend on the Gnome version.  But judging from what Totto just said, some library versions may differ between different distros.

**Comment by justperfection** [comment]
> Clutter 12 vs. 13 had breaking changes, if we support multiple distros, can we assure, that only v 13 is loaded without using
versioned imports????

Clutter dependency isn't related to the distros. GNOME Shell 45 uses [Clutter 13](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/8d7dc098b158be0a9f980fed97cad9031287e642/meson.build#L13).

> So is there an official list, from EXACT version that ship with each distro on GNOME???

- [meson](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/8d7dc098b158be0a9f980fed97cad9031287e642/meson.build)
- [dependencies](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/8d7dc098b158be0a9f980fed97cad9031287e642/js/misc/dependencies.js)

> Please explain to me, why exactly version are bad, since I don't get it???

In GNOME Shell process, versions getting specified on initiation. In prefs, it will happen by the parent module.

>  like mentioned with the GDa example

For `Gda` you can use `version` since it's not part of GNOME Shell dependencies.

**Comment by Totto16** [comment]
> > Clutter 12 vs. 13 had breaking changes, if we support multiple distros, can we assure, that only v 13 is loaded without using
> > versioned imports????
> 
> Clutter dependency isn't related to the distros. GNOME Shell 45 uses [Clutter 13](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/8d7dc098b158be0a9f980fed97cad9031287e642/meson.build#L13).
> 
> > So is there an official list, from EXACT version that ship with each distro on GNOME???
> 
>     * [meson](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/8d7dc098b158be0a9f980fed97cad9031287e642/meson.build)
> 
>     * [dependencies](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/8d7dc098b158be0a9f980fed97cad9031287e642/js/misc/dependencies.js)
> 
> 
> > Please explain to me, why exactly version are bad, since I don't get it???
> 
> In GNOME Shell process, versions getting specified on initiation. In prefs, it will happen by the parent module.
> 
> > like mentioned with the GDa example
> 
> For `Gda` you can use `version` since it's not part of GNOME Shell dependencies.

Ok thank you ❤️

**Pull request merged**
