### PR TITLE
Improve style and icons

### PR DESCRIPTION
**Pull request by daudix-UFO**
Some minor style changes to make the extension look more in place with GNOME

- Replace clipboard content icons with the GNOME ones
- Improve indicator icons
- Improve incognito mode icon
- Create new placeholder images to be in GNOME style (at least I tried)
- Change some colors
- Change content font to Cantarell
- Change text font to Monospace
- Fix icons not being recolored by adding `-symbolic` in the file name

image
image
##
image
image
image

### CODE REVIEW

**Comment by oae** [comment]
I have made all items customizable through the settings. Can you pull the latest version?

**Comment by daudix-UFO** [comment]
I think it should be fine now

**Comment by oae** [comment]
This looks really good. Thank you very much.

**Comment by daudix-UFO** [comment]
I'm glad you liked it :D

**Pull request merged**
