### PR TITLE
Update uk.po

### PR DESCRIPTION
**Pull request by OriginalSimon**
## Description

Ukrainian translation update

### CODE REVIEW

**Comment by Totto16** [comment]
Some time ago there was a bad Ukrainian translation in gnome if I remember correctly, So we'll be checking this rigorously (even if we don't speak Ukrainian 😓 ) 

But from the first look this seems good ❤️

**Comment by Totto16** [comment]
@bigbruno You contributed to this file earlier (https://github.com/oae/gnome-shell-pano/commit/e521675958e1c276cce9febb91f8fe80ef2d6c55), did you use google translate or something similar or do you understand Ukrainian?

**Comment by OriginalSimon** [comment]
Yes, I also heard about that situation. As far as I know, it was related to the fact that the translations included statements reflecting the position of the Ukrainian people, which caused discontent among some Russian users. In my work on translating software, I adhere to a neutral approach and avoid including political or controversial statements.

**Review by Totto16 — APPROVED** [review]
This seems all good. Thank you for your contribution ❤️ 

I'll wait a few days for a response from the previous creator of the translation, otherwise I'll merge it.

**Comment by OriginalSimon** [comment]
Please use ChatGPT for translation, as Google Translate often provides lower quality translations. I had to make corrections to the previous translator's work. Thank you!

**Comment by Totto16** [comment]
> Please use ChatGPT for translation, as Google Translate often provides lower quality translations. I had to make corrections to the previous translator's work. Thank you!

Most of these existing translations were made pre ChatGPT 😓

**Pull request merged**
